"""
Revit Height Restriction Script for R1 Zoning
Maximum Height: 35 feet
Generated by Building Code GPT
"""

import clr
clr.AddReference('RevitAPI')
clr.AddReference('RevitAPIUI')
from Autodesk.Revit.DB import *
from Autodesk.Revit.UI import *

def apply_height_restrictions(doc):
    """Apply height restrictions for R1 zoning"""
    
    max_height_ft = 35
    element_categories = ['Walls', 'Columns']
    modified_count = 0
    
    with Transaction(doc, "Apply Height Restrictions - R1") as t:
        t.Start()
        
        for category_name in element_categories:
            # Get elements by category
            if category_name == "Walls":
                category = BuiltInCategory.OST_Walls
            elif category_name == "Columns":
                category = BuiltInCategory.OST_Columns
            elif category_name == "Structural Framing":
                category = BuiltInCategory.OST_StructuralFraming
            elif category_name == "Roofs":
                category = BuiltInCategory.OST_Roofs
            else:
                continue
            
            # Collect elements
            collector = FilteredElementCollector(doc)
            elements = collector.OfCategory(category).WhereElementIsNotElementType().ToElements()
            
            for element in elements:
                try:
                    # Get element height parameter
                    height_param = element.get_Parameter(BuiltInParameter.INSTANCE_LENGTH_PARAM)
                    if height_param and height_param.AsDouble() > max_height_ft:
                        height_param.Set(max_height_ft)
                        modified_count += 1
                except:
                    continue
        
        t.Commit()
    
    TaskDialog.Show("Height Restrictions Applied", 
                   f"Modified {modified_count} elements to comply with R1 height limit of 35 feet")
    return modified_count

# Execute the function
if __name__ == "__main__":
    doc = __revit__.ActiveUIDocument.Document
    apply_height_restrictions(doc)
