"""
Revit API Script Template
Generated by Building Code GPT MCP Integration
"""

import clr
clr.AddReference('RevitAPI')
clr.AddReference('RevitAPIUI')
from Autodesk.Revit.DB import *
from Autodesk.Revit.UI import *

def main():
    """Main script function"""
    try:
        # Get current document
        doc = __revit__.ActiveUIDocument.Document
        
        # Your code here
        TaskDialog.Show("Success", "Script executed successfully")
        
    except Exception as e:
        TaskDialog.Show("Error", f"Script failed: {str(e)}")

if __name__ == "__main__":
    main()